variables:
  homepage: https://github.com/caarlos0/domain_exporter
  repository: https://github.com/caarlos0/domain_exporter
  description: Exports the expiration time of your domains in the Prometheus format.
includes:
  - from_url:
      url: https://raw.githubusercontent.com/caarlos0/goreleaserfiles/main/build.yml
  - from_url:
      url: https://raw.githubusercontent.com/caarlos0/goreleaserfiles/main/release.yml
  - from_url:
      url: https://raw.githubusercontent.com/caarlos0/goreleaserfiles/main/package.yml
  - from_url:
      url: https://raw.githubusercontent.com/caarlos0/goreleaserfiles/main/podman.yml

before:
  hooks:
    - go mod tidy

furies:
- account: caarlos0
